# Generated by Django 5.0 on 2024-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('categoria', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=20)),
                ('ramo', models.CharField(max_length=100)),
                ('data_pesquisa', models.DateField()),
                ('cliente1', models.CharField(max_length=100)),
                ('cliente2', models.CharField(max_length=100)),
                ('cliente3', models.CharField(max_length=100)),
            ],
        ),
    ]
