# Generated by Django 5.0 on 2024-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_page', '0002_fornecedor_tempo_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='tempo_atividade',
            field=models.CharField(choices=[('opcao0', 'Selecione'), ('opcao1', 'até 2 anos'), ('opcao2', '02 à 05 anos'), ('opcao3', '05 à 10 anos'), ('opcao4', '+10 anos')], default='opcao1', max_length=100),
        ),
    ]
