# Generated by Django 5.0 on 2024-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_page', '0004_remove_fornecedor_ramo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='tempo_atividade',
            field=models.CharField(choices=[('Selecione', 'Selecione'), ('até 2 anos', 'até 2 anos'), ('02 à 05 anos', '02 à 05 anos'), ('05 à 10 anos', '05 à 10 anos'), ('+10 anos', '+10 anos')], default='Selecione', max_length=100),
        ),
    ]
